FROM node:20-alpine AS base

WORKDIR /app

ENV NODE_ENV=development

RUN apk add --no-cache libc6-compat

COPY frontend/package*.json ./

RUN if [ -f package.json ]; then npm install; fi

COPY frontend ./

EXPOSE 3000

CMD ["npm", "run", "dev"]
